# Generated by Django 5.0.3 on 2025-09-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_owner_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('in_person', 'In-Person'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='virtual_link',
            field=models.URLField(blank=True, help_text='Zoom/Teams/Meet link for virtual events'),
        ),
        migrations.AddField(
            model_name='event',
            name='virtual_meeting_id',
            field=models.CharField(blank=True, help_text='Meeting ID for virtual events', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='virtual_passcode',
            field=models.CharField(blank=True, help_text='Meeting passcode (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='virtual_platform',
            field=models.CharField(blank=True, help_text='Platform (Zoom, Teams, Meet, etc.)', max_length=50),
        ),
    ]
