# Generated by Django 5.0.3 on 2025-04-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='ticket_format',
            field=models.CharField(choices=[('HTML', 'HTML'), ('PDF', 'PDF'), ('BOTH', 'Both')], default='BOTH', max_length=10),
        ),
        migrations.AddField(
            model_name='invitation',
            name='ticket_html',
            field=models.FileField(blank=True, null=True, upload_to='tickets/html/'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/pdf/'),
        ),
    ]
