# Generated by Django 5.0.3 on 2025-09-08 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_type_event_virtual_link_and_more'),
        ('networking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='connection',
            name='networking__from_us_24c7a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='connection',
            name='networking__to_user_5a155f_idx',
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['from_user', 'event', 'status'], name='networking__from_us_09727f_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['to_user', 'event', 'status'], name='networking__to_user_e57678_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['status', 'connected_at'], name='networking__status_dadbe2_idx'),
        ),
    ]
