# Generated by Django 5.0.3 on 2025-09-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='gamification_processed',
            field=models.BooleanField(default=False),
        ),
    ]
