# Generated by Django 5.0.3 on 2025-09-13 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_message_recipient_email_message_recipient_invitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='icebreakeractivity',
            name='allow_multiple_responses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='icebreakeractivity',
            name='anonymous_responses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='icebreakeractivity',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show prominently in the app'),
        ),
        migrations.AddField(
            model_name='icebreakeractivity',
            name='response_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icebreakeractivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='icebreakeractivity',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icebreakerresponse',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icebreakerresponse',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icebreakerresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='icebreakeractivity',
            name='activity_type',
            field=models.CharField(choices=[('poll', 'Poll'), ('quiz', 'Quiz'), ('question', 'Question'), ('challenge', 'Challenge'), ('introduction', 'Introduction'), ('prediction', 'Event Prediction'), ('skill_sharing', 'Skill Sharing'), ('goal_setting', 'Goal Setting'), ('fun_fact', 'Fun Fact Sharing'), ('networking_challenge', 'Networking Challenge')], default='question', max_length=20),
        ),
        migrations.CreateModel(
            name='IcebreakerResponseReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communication.icebreakerresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Icebreaker Response Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IcebreakerResponseLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='communication.icebreakerresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('response', 'user')},
            },
        ),
    ]
