# Generated by Django 5.0.3 on 2025-09-13 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_extend_icebreaker_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='icebreakerresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='icebreakeractivity',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether invitation emails were sent'),
        ),
        migrations.AddField(
            model_name='icebreakeractivity',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When invitation emails were sent', null=True),
        ),
        migrations.AddField(
            model_name='icebreakeractivity',
            name='guest_response_token',
            field=models.CharField(blank=True, help_text='Unique token for guest access', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='icebreakeractivity',
            name='send_email_on_create',
            field=models.BooleanField(default=True, help_text='Send emails to invitees when activity is created'),
        ),
        migrations.AddField(
            model_name='icebreakerresponse',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email for guest responses', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='icebreakerresponse',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Name for guest responses', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='icebreakerresponse',
            name='is_guest_response',
            field=models.BooleanField(default=False, help_text='Whether this is a guest response'),
        ),
        migrations.AlterField(
            model_name='icebreakerresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icebreaker_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
