# Generated by Django 5.0.3 on 2025-09-14 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_enhanced_gamification'),
        ('events', '0003_event_event_type_event_virtual_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergamificationprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usergamificationprofile',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email for guest users', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usergamificationprofile',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Name for guest users', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usergamificationprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icebreaker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usergamificationprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'event'), name='unique_user_event'),
        ),
        migrations.AddConstraint(
            model_name='usergamificationprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_email__isnull', False)), fields=('guest_email', 'event'), name='unique_guest_email_event'),
        ),
    ]
