name: Claude Comprehensive Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  claude-security-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Security Review with Claude
        uses: anthropics/claude-code-review@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          focus_areas: "security,vulnerability-detection,authentication,authorization,data-validation"
          review_style: "comprehensive"
          max_files: 50
          comment_prefix: "🔒 **Security Review**"

  claude-architecture-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Architecture Review with Claude
        uses: anthropics/claude-code-review@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          focus_areas: "architecture,design-patterns,scalability,maintainability,code-organization"
          review_style: "comprehensive"
          max_files: 50
          comment_prefix: "🏗️ **Architecture Review**"

  claude-django-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Django Best Practices Review
        uses: anthropics/claude-code-review@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          focus_areas: "django-best-practices,orm-optimization,api-design,model-design,signal-handling"
          review_style: "comprehensive" 
          languages: "python"
          max_files: 50
          comment_prefix: "🐍 **Django Review**"
          include_patterns: |
            backend/**/*.py
            **/models.py
            **/views.py
            **/serializers.py
            **/urls.py
            **/signals.py

  claude-frontend-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Frontend Review
        uses: anthropics/claude-code-review@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          focus_areas: "react-best-practices,typescript-quality,performance,accessibility,user-experience"
          review_style: "standard"
          languages: "typescript,javascript,jsx,tsx"
          max_files: 30
          comment_prefix: "⚛️ **Frontend Review**"
          include_patterns: |
            frontend/**/*
            **/*.tsx
            **/*.jsx
            **/*.ts
            **/*.js

  claude-performance-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Performance Review
        uses: anthropics/claude-code-review@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          focus_areas: "performance,database-optimization,caching,memory-usage,query-optimization"
          review_style: "standard"
          max_files: 50
          comment_prefix: "⚡ **Performance Review**"