name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Claude Code Review
        uses: anthropics/claude-code-review@v1
        with:
          # Required: Your Anthropic API key
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Optional: GitHub token for posting comments (defaults to GITHUB_TOKEN)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Optional: Review focus areas (comma-separated)
          focus_areas: "security,performance,code-quality,best-practices"
          
          # Optional: Maximum files to review (default: 50)
          max_files: 100
          
          # Optional: Programming languages to focus on
          languages: "python,javascript,typescript,dockerfile"
          
          # Optional: Review style
          review_style: "comprehensive"  # options: brief, standard, comprehensive
          
          # Optional: Include suggestions for improvements
          include_suggestions: true
          
          # Optional: Skip files matching these patterns
          exclude_patterns: |
            **/*.min.js
            **/node_modules/**
            **/__pycache__/**
            **/migrations/**
            **/*.pyc
            **/staticfiles/**
            **/media/**
            **/.git/**

      - name: Comment on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Check if review results exist
            const reviewPath = path.join(process.env.GITHUB_WORKSPACE, 'claude-review.md');
            if (fs.existsSync(reviewPath)) {
              const reviewContent = fs.readFileSync(reviewPath, 'utf8');
              
              // Post review as PR comment
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🤖 Claude Code Review\n\n${reviewContent}`
              });
            } else {
              console.log('No review results found');
            }